const QUESTIONS = [
  {
    id: 'q1',
    question_type: 'triad',
    prompt: ['Asthma', 'Eosinophilia', 'Sinusitis'],
    category: 'Pulmonology',
    difficulty_level: 2,
    accepted_answers: ['eosinophilic granulomatosis with polyangiitis', 'egpa', 'churg-strauss syndrome'],
    definition: 'A necrotizing vasculitis affecting small vessels in patients with asthma and prominent eosinophilia.',
    hallmark_features: ['Three-phase presentation: asthma → eosinophilia → necrotizing vasculitis', 'Peripheral neuropathy (especially mononeuritis multiplex)', 'Cardiac involvement with granulomas', 'p-ANCA positive (MPO antibodies)'],
    exam_pearl: 'Think of EGPA when you see the triad of asthma, eosinophilia, and systemic manifestations.',
    pitfall: 'Often confused with allergic bronchopulmonary aspergillosis (ABPA), but EGPA has vasculitis.'
  },
  {
    id: 'q2',
    question_type: 'pathognomonic',
    prompt: 'Koebner phenomenon - new skin lesions triggered by trauma in a plaque-forming disease.',
    category: 'Dermatology',
    difficulty_level: 1,
    accepted_answers: ['psoriasis'],
    definition: 'A chronic autoimmune inflammatory skin disease characterized by red, scaly plaques.',
    hallmark_features: ['Koebner phenomenon (lesions at sites of trauma)', 'Auspitz sign (bleeding when scale is removed)', 'Nail involvement (pitting, onycholysis)', 'Symmetric distribution on extensor surfaces'],
    exam_pearl: 'Psoriasis is the classic disease showing Koebner phenomenon - think trauma → new lesions.',
    pitfall: 'Do not confuse with eczema, which has lichenification rather than plaques.'
  },
  {
    id: 'q3',
    question_type: 'best_answer',
    prompt: 'A 45-year-old man presents with chest pain and elevated troponin. ECG shows ST elevation in leads II, III, and aVF. What is the culprit artery?',
    category: 'Cardiology',
    difficulty_level: 2,
    options: ['LAD', 'RCA', 'LCx', 'Left main'],
    accepted_answers: ['rca', 'right coronary artery'],
    definition: 'Inferior wall myocardial infarction caused by occlusion of the right coronary artery.',
    hallmark_features: ['ST elevation in II, III, aVF', 'Often associated with RV involvement', 'May have bradycardia and hypotension', 'High mortality if not reperfused quickly'],
    exam_pearl: 'Inferior MI (II, III, aVF) = RCA in 80% of patients (or LCx in left dominance).',
    pitfall: 'Do not forget to check for RV involvement - it changes management (avoid nitrates, give fluids).'
  },
  {
    id: 'q4',
    question_type: 'triad',
    prompt: ['Fever', 'Rash', 'Joint pain'],
    category: 'Rheumatology',
    difficulty_level: 2,
    accepted_answers: ['systemic lupus erythematosus', 'sle'],
    definition: 'A systemic autoimmune disease affecting multiple organ systems with autoantibodies.',
    hallmark_features: ['Malar rash (butterfly rash)', 'Discoid rash', 'Photosensitivity', 'Positive ANA and anti-dsDNA antibodies'],
    exam_pearl: 'Think SLE in young women with fever, rash, and arthritis - check ANA and anti-dsDNA.',
    pitfall: 'Not all positive ANAs mean SLE - need clinical criteria. ANA is sensitive but not specific.'
  },
  {
    id: 'q5',
    question_type: 'pathognomonic',
    prompt: 'Auer rods - abnormal myeloid differentiation with rod-shaped inclusions in leukemic blasts.',
    category: 'Hematology',
    difficulty_level: 2,
    accepted_answers: ['acute myeloid leukemia', 'aml'],
    definition: 'A malignancy of myeloid progenitor cells with abnormal blasts in bone marrow and blood.',
    hallmark_features: ['>20% blasts in bone marrow', 'Auer rods (pathognomonic)', 'Cytochemical stains positive', 'Various cytogenetic abnormalities'],
    exam_pearl: 'If you see Auer rods, think AML - they are virtually pathognomonic for AML.',
    pitfall: 'Do not confuse AML with ALL - AML has Auer rods, ALL does not.'
  },
  {
    id: 'q6',
    question_type: 'best_answer',
    prompt: 'A 6-year-old with sudden-onset stridor and drooling. What is the most likely diagnosis?',
    category: 'Pediatrics',
    difficulty_level: 2,
    options: ['Croup', 'Epiglottitis', 'Foreign body', 'Retropharyngeal abscess'],
    accepted_answers: ['epiglottitis'],
    definition: 'Acute inflammation of the epiglottis, a medical emergency requiring airway management.',
    hallmark_features: ['"Thumbprint" sign on neck X-ray', 'Tripod positioning', 'Drooling and difficulty swallowing', 'High fever and toxic appearance'],
    exam_pearl: 'Epiglottitis is a medical emergency - do NOT examine throat with tongue depressor without airway ready.',
    pitfall: 'Do not delay intubation to get imaging - clinical suspicion is enough to secure airway.'
  },
  {
    id: 'q7',
    question_type: 'triad',
    prompt: ['Elevated glucose', 'Ketones', 'Acidosis'],
    category: 'Endocrinology',
    difficulty_level: 1,
    accepted_answers: ['diabetic ketoacidosis', 'dka'],
    definition: 'Severe complication of diabetes with hyperglycemia, ketonemia, and metabolic acidosis.',
    hallmark_features: ['Anion gap metabolic acidosis', 'Elevated beta-hydroxybutyrate', 'Kussmaul respirations', 'Fruity breath odor'],
    exam_pearl: 'DKA triad: hyperglycemia + ketonemia + metabolic acidosis. Treat with fluids, insulin, and K+.',
    pitfall: 'Do not forget hypokalemia despite high serum K+ - total body K is depleted.'
  },
  {
    id: 'q8',
    question_type: 'pathognomonic',
    prompt: 'Waterhouse-Friderichsen syndrome - fulminant sepsis with bilateral adrenal hemorrhage and shock.',
    category: 'Infectious Disease',
    difficulty_level: 2,
    accepted_answers: ['neisseria meningitidis', 'meningococcal sepsis'],
    definition: 'Acute sepsis caused by Neisseria meningitidis with hemorrhagic necrosis of adrenal glands.',
    hallmark_features: ['Petechial rash (can become confluent purpura)', 'Sudden onset of shock', 'Bilateral adrenal hemorrhage on imaging', 'High mortality if not treated immediately'],
    exam_pearl: 'Waterhouse-Friderichsen = meningococcemia. See petechiae + shock = give antibiotics before imaging.',
    pitfall: 'Do not wait for LP or blood cultures - start antibiotics immediately in suspected meningococcemia.'
  },
  {
    id: 'q9',
    question_type: 'best_answer',
    prompt: 'Elevated transaminases > 1000 U/L with normal bilirubin. What is the most likely cause?',
    category: 'Gastroenterology',
    difficulty_level: 2,
    options: ['Viral hepatitis', 'Acetaminophen toxicity', 'Cirrhosis', 'Biliary obstruction'],
    accepted_answers: ['acetaminophen toxicity'],
    definition: 'Acute liver injury from acetaminophen overdose with massive hepatocyte necrosis.',
    hallmark_features: ['Transaminases > 1000 (often >5000)', 'Normal or slightly elevated bilirubin initially', 'Elevated INR', 'Acute liver failure in severe cases'],
    exam_pearl: 'Very high transaminases (>1000) think viral hepatitis or acetaminophen - get level and INR.',
    pitfall: 'Bilirubin rises slowly - early in course may be normal despite severe hepatocellular injury.'
  },
  {
    id: 'q10',
    question_type: 'triad',
    prompt: ['Hypercalcemia', 'Elevated PTH', 'Nephrolithiasis'],
    category: 'Nephrology',
    difficulty_level: 2,
    accepted_answers: ['primary hyperparathyroidism'],
    definition: 'Endocrine disorder with excessive PTH secretion causing hypercalcemia and bone disease.',
    hallmark_features: ['Hypercalcemia with high or normal PTH', 'Nephrolithiasis (calcium stones)', 'Osteitis fibrosa cystica', 'Hypophosphatemia'],
    exam_pearl: 'Hypercalcemia + HIGH PTH = primary hyperparathyroidism. Most common cause of hypercalcemia outpatient.',
    pitfall: 'Do not confuse with humoral hypercalcemia of malignancy where PTH is suppressed.'
  },
  {
    id: 'q11',
    question_type: 'pathognomonic',
    prompt: 'Splinter hemorrhages - linear hemorrhages under fingernails in a patient with fever and new murmur.',
    category: 'Cardiology',
    difficulty_level: 2,
    accepted_answers: ['infective endocarditis', 'bacterial endocarditis'],
    definition: 'Infection of heart valves or endocardium, typically from bacteria seeding during bacteremia.',
    hallmark_features: ['Osler nodes (painful nodules on fingertips)', 'Janeway lesions (painless hemorrhagic macules)', 'Splinter hemorrhages', 'Roth spots on retina'],
    exam_pearl: 'Splinter hemorrhages are part of peripheral stigmata of endocarditis - use Duke criteria for diagnosis.',
    pitfall: 'Not all splinter hemorrhages are from endocarditis - trauma can cause them too.'
  },
  {
    id: 'q12',
    question_type: 'best_answer',
    prompt: 'A 55-year-old smoker with COPD presents with hemoptysis. Chest X-ray shows a cavitary lesion in the apex. What organism should you cover?',
    category: 'Pulmonology',
    difficulty_level: 2,
    options: ['Streptococcus pneumoniae', 'Mycobacterium tuberculosis', 'Pseudomonas aeruginosa', 'Candida'],
    accepted_answers: ['mycobacterium tuberculosis', 'tuberculosis', 'tb'],
    definition: 'Chronic respiratory infection caused by Mycobacterium tuberculosis, transmitted via airborne droplets.',
    hallmark_features: ['Apical cavitary lesions', 'Hemoptysis', 'Night sweats and weight loss', 'Positive AFB smear'],
    exam_pearl: 'Cavitary lesion + apex + hemoptysis = TB until proven otherwise. Get AFB smear and cultures.',
    pitfall: 'TB can have minimal symptoms initially - high index of suspicion needed in risk groups.'
  },
  {
    id: 'q13',
    question_type: 'triad',
    prompt: ['Pruritus', 'Petechiae', 'Thrombocytopenia'],
    category: 'Hematology',
    difficulty_level: 2,
    accepted_answers: ['immune thrombocytopenia', 'itp'],
    definition: 'Autoimmune destruction of platelets causing bleeding and thrombocytopenia.',
    hallmark_features: ['Platelet count <150,000', 'Petechiae and purpura', 'No splenomegaly', 'Normal bone marrow'],
    exam_pearl: 'Isolated thrombocytopenia with petechiae = ITP. Check bone marrow to rule out other causes.',
    pitfall: 'Do not confuse ITP with TTP - TTP has fever, hemolytic anemia, and renal dysfunction.'
  },
  {
    id: 'q14',
    question_type: 'pathognomonic',
    prompt: 'Klinefelter syndrome - gynecomastia, small testes, and azoospermia in a tall man.',
    category: 'Genetics',
    difficulty_level: 2,
    accepted_answers: ['klinefelter syndrome', '47 xxy'],
    definition: 'Most common sex chromosome disorder in males with 47,XXY karyotype.',
    hallmark_features: ['Small firm testes (<3.5 cm)', 'Azoospermia', 'Tall stature with long legs', 'Gynecomastia'],
    exam_pearl: 'Klinefelter: tall, infertile, gynecomastia, small testes. Check karyotype if suspected.',
    pitfall: 'Most men with Klinefelter are not diagnosed - think of it in infertile men with small testes.'
  },
  {
    id: 'q15',
    question_type: 'best_answer',
    prompt: 'A patient with acute angle-closure glaucoma has dilated pupil and severe pain. What is the initial treatment?',
    category: 'Ophthalmology',
    difficulty_level: 2,
    options: ['Atropine', 'Pilocarpine', 'Timolol', 'Laser'],
    accepted_answers: ['pilocarpine'],
    definition: 'Medical emergency with sudden rise in intraocular pressure from angle closure.',
    hallmark_features: ['Mid-dilated, fixed pupil', 'Severe eye pain', 'Blurred vision', 'Hazy cornea'],
    exam_pearl: 'Acute angle closure = pilocarpine (constrict pupil) + timolol + acetazolamide. Laser definitive.',
    pitfall: 'Do not use atropine in angle closure - it causes mydriasis and worsens angle closure.'
  },
  {
    id: 'q16',
    question_type: 'triad',
    prompt: ['Hypotension', 'Jugular venous distention', 'Muffled heart sounds'],
    category: 'Cardiology',
    difficulty_level: 1,
    accepted_answers: ['cardiac tamponade', 'pericardial effusion'],
    definition: 'Life-threatening accumulation of fluid in pericardial space causing circulatory compromise.',
    hallmark_features: ['Beck triad: hypotension, JVD, muffled heart sounds', 'Pulsus paradoxus', 'Tachycardia', 'Elevated JVP'],
    exam_pearl: 'Beck triad is classic for cardiac tamponade - pericardiocentesis is life-saving.',
    pitfall: 'Do not miss tamponade in patients with malignancy, trauma, or dialysis - check with echo.'
  },
  {
    id: 'q17',
    question_type: 'pathognomonic',
    prompt: 'Starry sky appearance - diffuse infiltration by small blue cells in a rapidly growing tumor.',
    category: 'Oncology',
    difficulty_level: 2,
    accepted_answers: ['burkitt lymphoma'],
    definition: 'Aggressive B-cell lymphoma associated with t(8;14) translocation and MYC oncogene.',
    hallmark_features: ['Translocation t(8;14) (MYC on chromosome 8)', 'Rapid growth and high mortality if untreated', 'May present with jaw mass or abdominal mass', 'Associated with EBV'],
    exam_pearl: 'Burkitt lymphoma: starry sky histology, t(8;14), rapid growth. Requires aggressive chemotherapy.',
    pitfall: 'Burkitt is highly curable if treated early - do not underestimate aggressive lymphomas.'
  },
  {
    id: 'q18',
    question_type: 'best_answer',
    prompt: 'A 30-year-old woman with history of DVT now presents with sudden dyspnea and chest pain. What is the next immediate step?',
    category: 'Pulmonology',
    difficulty_level: 2,
    options: ['Chest X-ray', 'D-dimer', 'CT angiography', 'Echocardiogram'],
    accepted_answers: ['ct angiography', 'cta'],
    definition: 'Acute obstruction of pulmonary arteries by thrombi, usually from DVT.',
    hallmark_features: ['Acute dyspnea and chest pain', 'Tachycardia and hypoxia', 'Elevated D-dimer', 'Hampton hump on CXR'],
    exam_pearl: 'Suspected PE = get CTA PE protocol. D-dimer useful for ruling out low-risk PE, not diagnostic.',
    pitfall: 'Do not rely on CXR alone - can be normal in PE. Use clinical judgment and CTA.'
  },
  {
    id: 'q19',
    question_type: 'triad',
    prompt: ['Diarrhea', 'Dermatitis', 'Dementia'],
    category: 'Neurology',
    difficulty_level: 2,
    accepted_answers: ['pellagra', 'niacin deficiency'],
    definition: 'Disease caused by niacin (vitamin B3) deficiency, seen in malnutrition.',
    hallmark_features: ['4 Ds: dermatitis, diarrhea, dementia, death', 'Hyperpigmentation on sun-exposed areas', 'Glossitis', 'Photosensitive dermatitis'],
    exam_pearl: 'Remember the 4 Ds of pellagra - think niacin deficiency in malnourished patients.',
    pitfall: 'Pellagra is rare in developed countries but still important in populations with malnutrition.'
  },
  {
    id: 'q20',
    question_type: 'pathognomonic',
    prompt: 'Cherry red spot on macula - retinal whitening with red foveola in a patient with progressive neurological decline.',
    category: 'Neurology',
    difficulty_level: 2,
    accepted_answers: ['central retinal artery occlusion', 'lysosomal storage disease'],
    definition: 'Characteristic retinal finding in acute CRAO or lysosomal storage diseases.',
    hallmark_features: ['Cherry red spot at fovea', 'Pale retina surrounding it', 'Sudden vision loss (in CRAO)', 'Can be seen in CRAO or storage diseases'],
    exam_pearl: 'Cherry red spot = think CRAO if acute vision loss, or storage disease if progressive.',
    pitfall: 'Cherry red spot in storage disease is not an emergency but indicates serious condition.'
  },
  {
    id: 'q21',
    question_type: 'best_answer',
    prompt: 'A 40-year-old man with cirrhosis presents with hematemesis. What is the most likely source?',
    category: 'Gastroenterology',
    difficulty_level: 2,
    options: ['Gastric ulcer', 'Esophageal varices', 'Mallory-Weiss tear', 'Dieulafoy lesion'],
    accepted_answers: ['esophageal varices'],
    definition: 'Dilated veins in esophagus from portal hypertension, prone to massive bleeding.',
    hallmark_features: ['Portal hypertension', 'Painless bleeding', 'High mortality if ruptured', 'Visible on endoscopy'],
    exam_pearl: 'Cirrhosis + hematemesis = esophageal varices until proven otherwise. Band ligation is treatment.',
    pitfall: 'Do not delay endoscopy - variceal bleeding requires urgent intervention.'
  },
  {
    id: 'q22',
    question_type: 'triad',
    prompt: ['Headache', 'Neck stiffness', 'Photophobia'],
    category: 'Neurology',
    difficulty_level: 1,
    accepted_answers: ['meningitis', 'bacterial meningitis'],
    definition: 'Inflammation of meninges, can be viral or bacterial, medical emergency if bacterial.',
    hallmark_features: ['Meningeal signs (neck stiffness, Kernig sign, Brudzinski sign)', 'CSF pleocytosis', 'Petechial rash in meningococcal disease', 'Positive cultures'],
    exam_pearl: 'Classic meningitis triad - but meningitis is a clinical diagnosis. Start antibiotics before LP if concern.',
    pitfall: 'Do not delay antibiotics while waiting for imaging or LP - mortality increases with delay.'
  },
  {
    id: 'q23',
    question_type: 'pathognomonic',
    prompt: 'Xanthoma - lipid deposits in skin causing yellow nodules, seen in hyperlipidemia.',
    category: 'Dermatology',
    difficulty_level: 2,
    accepted_answers: ['familial hypercholesterolemia', 'hyperlipidemia'],
    definition: 'Genetic disorder of lipid metabolism causing very high cholesterol and premature CAD.',
    hallmark_features: ['Xanthomas on knees, elbows, Achilles tendon', 'Corneal arcus', 'Total cholesterol >300 mg/dL', 'Premature MI'],
    exam_pearl: 'Xanthomas indicate severe hyperlipidemia - screen for familial hypercholesterolemia.',
    pitfall: 'Treat aggressively - familial hypercholesterolemia has high risk of early MI and needs statins.'
  },
  {
    id: 'q24',
    question_type: 'best_answer',
    prompt: 'A 60-year-old man with new-onset seizure. MRI shows ring-enhancing lesion with surrounding edema. What is the most likely diagnosis?',
    category: 'Neurology',
    difficulty_level: 2,
    options: ['Glioblastoma', 'Brain abscess', 'Tuberculoma', 'Metastasis'],
    accepted_answers: ['brain abscess'],
    definition: 'Localized collection of pus in brain from hematogenous spread or direct extension of infection.',
    hallmark_features: ['Ring enhancement on imaging', 'Seizures', 'Headache', 'Fever may be absent'],
    exam_pearl: 'Ring-enhancing lesion + fever = think brain abscess. Get blood cultures and imaging.',
    pitfall: 'Brain abscess can mimic malignancy - biopsy or culture may be needed for diagnosis.'
  },
  {
    id: 'q25',
    question_type: 'triad',
    prompt: ['Steatorrhea', 'Weight loss', 'Vitamin deficiencies'],
    category: 'Gastroenterology',
    difficulty_level: 2,
    accepted_answers: ['celiac disease'],
    definition: 'Autoimmune disorder triggered by gluten causing small intestinal villous atrophy.',
    hallmark_features: ['Malabsorption', 'Chronic diarrhea', 'Dermatitis herpetiformis', 'Elevated tissue transglutaminase (tTG) antibodies'],
    exam_pearl: 'Think celiac in anyone with malabsorption or unexplained anemia - screen with serology.',
    pitfall: 'Do not miss celiac in atypical presentations - can present with osteoporosis, infertility, or neurologic symptoms.'
  }
];

export { QUESTIONS };
