-- Seed initial questions from Quizpital
INSERT INTO public.questions (question_id, question_type, prompt, category, difficulty_level, accepted_answers, definition, hallmark_features, exam_pearl, pitfall)
VALUES
  ('q1', 'triad', '["High fever", "Severe pharyngitis", "Hypotension"]', 'Infectious Disease', 1, ARRAY['Scarlet fever'], 'Group A Streptococcus infection causing acute pharyngitis with systemic manifestations', ARRAY['Strawberry tongue', 'Sandpaper rash', 'Pastia lines'], 'Treat early with penicillin to prevent rheumatic fever complications.', 'Do not confuse rash with measles or rubella.'),
  
  ('q2', 'pathognomonic', '["Koplik spots"]', 'Infectious Disease', 2, ARRAY['Measles'], 'Viral exanthem caused by paramyxovirus with respiratory spread', ARRAY['Cough, coryza, conjunctivitis', '3-day fever before rash', 'Maculopapular rash'], 'Koplik spots (white spots on buccal mucosa) precede the rash by 2-3 days.', 'Measles can be prevented by MMR vaccination.'),
  
  ('q3', 'best_answer', 'A 3-year-old presents with fever, drooling, and difficulty breathing. Which diagnosis is most likely?', 'Pediatrics', 2, ARRAY['Epiglottitis'], ARRAY['A) Croup', 'B) Epiglottitis', 'C) Laryngitis', 'D) Tracheitis'], 'Acute inflammation of epiglottis causing airway obstruction', ARRAY['Tripod positioning', 'Stridor', 'Drooling'], 'Epiglottitis is a medical emergency requiring airway management before diagnosis.', 'Do not examine the throat without airway backup.'),
  
  ('q4', 'triad', '["Blue lips", "Clubbing", "Squatting position"]', 'Cardiology', 2, ARRAY['Cyanotic heart disease', 'Tetralogy of Fallot'], 'Congenital heart defect with right-to-left shunt causing central cyanosis', ARRAY['Right ventricular hypertrophy', 'Boot-shaped heart on X-ray', 'Tet spells'], 'Squatting increases systemic vascular resistance, improving pulmonary blood flow.', 'Not all cyanosis is cardiac in origin.'),
  
  ('q5', 'pathognomonic', '["Crescent-shaped bacteria"]', 'Microbiology', 2, ARRAY['Vibrio cholerae'], 'Gram-negative curved rod causing severe watery diarrhea and dehydration', ARRAY['Rapid fluid loss', 'Rice-water stools', 'Severe electrolyte depletion'], 'Vibrio cholerae causes rice-water diarrhea that can lead to hypovolemic shock.', 'Cholera requires aggressive fluid and electrolyte replacement.'),
  
  ('q6', 'triad', '["Jaundice", "Dark urine", "Pale stools"]', 'Gastroenterology', 1, ARRAY['Biliary obstruction', 'Cholestasis'], 'Impaired bile flow causing accumulation of bilirubin and bile salts', ARRAY['Pruritus', 'Hepatomegaly', 'Right upper quadrant pain'], 'The combination of jaundice with dark urine and pale stools suggests post-hepatic obstruction.', 'Do not overlook gallstones as a cause of obstruction.'),
  
  ('q7', 'best_answer', 'A patient with chronic headaches has a "thunderclap" headache. What is the most important next step?', 'Neurology', 3, ARRAY['CT angiography of head'], ARRAY['A) Lumbar puncture', 'B) CT angiography', 'C) MRI brain', 'D) EEG'], 'Thunderclap headache suggests subarachnoid hemorrhage requiring emergency imaging', ARRAY['Neck stiffness', 'Photophobia', 'Altered consciousness'], 'Thunderclap headache is a medical emergency suggesting intracranial pathology.', 'Do not delay imaging to perform LP in suspected SAH.'),
  
  ('q8', 'pathognomonic', '["Splinter hemorrhages under nails"]', 'Cardiology', 2, ARRAY['Bacterial endocarditis'], 'Infection of heart valves causing septic emboli and vasculitis', ARRAY['Osler nodes (finger pads)', 'Janeway lesions (palms)', 'Roth spots (retina)'], 'Splinter hemorrhages are linear streaks under fingernails from septic emboli.', 'Not all splinter hemorrhages indicate endocarditis.'),
  
  ('q9', 'triad', '["Photophobia", "Neck stiffness", "Fever"]', 'Infectious Disease', 1, ARRAY['Meningitis'], 'Inflammation of the meninges causing CNS infection', ARRAY['Kernig sign positive', 'Brudzinski sign positive', 'Altered mental status'], 'Classic meningitis triad requires immediate LP and empiric antibiotics.', 'Do not delay antibiotics waiting for LP if meningitis is suspected.'),
  
  ('q10', 'best_answer', 'A 65-year-old male with sudden onset weakness on left side and slurred speech. What is the diagnosis?', 'Neurology', 1, ARRAY['Acute ischemic stroke'], ARRAY['A) Transient ischemic attack', 'B) Acute ischemic stroke', 'C) Hemorrhagic stroke', 'D) Todd paralysis'], 'Sudden neurologic deficit in distribution of cerebral artery territory', ARRAY['Aphasia or dysarthria', 'Facial droop', 'Arm weakness'], 'Time is brain - thrombolytics must be given within 4.5 hours of symptom onset.', 'Hemorrhagic stroke is ruled out before thrombolytics.'),
  
  ('q11', 'pathognomonic', '["Heliotrope rash around eyes"]', 'Rheumatology', 2, ARRAY['Dermatomyositis'], 'Autoimmune myositis with characteristic skin findings', ARRAY['Gottron papules on knuckles', 'Muscle weakness and pain', 'Elevated CK'], 'Heliotrope rash (purple/red around eyes) is pathognomonic for dermatomyositis.', 'Dermatomyositis can be associated with underlying malignancy.'),
  
  ('q12', 'triad', '["Hypercalcemia", "Hypophosphatemia", "Elevated PTH"]', 'Endocrinology', 2, ARRAY['Primary hyperparathyroidism'], 'Excessive PTH secretion causing calcium and phosphate abnormalities', ARRAY['Kidney stones', 'Osteoporosis', 'Peptic ulcer disease'], 'PTH is appropriately elevated in response to hypercalcemia in primary hyperparathyroidism.', 'Secondary hyperparathyroidism has normal or low calcium.'),
  
  ('q13', 'best_answer', 'A patient presents with tremor, anxiety, weight loss, and palpitations. Which hormone is likely elevated?', 'Endocrinology', 1, ARRAY['Free T4 and T3'], ARRAY['A) TSH', 'B) Free T4 and T3', 'C) Cortisol', 'D) Glucagon'], 'Thyrotoxicosis from excessive thyroid hormone production', ARRAY['Goiter', 'Eye exophthalmos (if Graves)', 'Warm, moist skin'], 'Excess thyroid hormone causes hypermetabolic state with sympathetic stimulation.', 'TSH is suppressed in primary hyperthyroidism.'),
  
  ('q14', 'pathognomonic', '["Barrel chest with pursed-lip breathing"]', 'Pulmonology', 2, ARRAY['COPD', 'Emphysema'], 'Chronic lung disease with air trapping and emphysematous changes', ARRAY['Decreased breath sounds', 'Prolonged expiration', 'Use of accessory muscles'], 'Pursed-lip breathing creates positive airway pressure to prevent small airway collapse.', 'Not all barrel chests indicate COPD.'),
  
  ('q15', 'triad', '["Dyspnea", "Orthopnea", "Peripheral edema"]', 'Cardiology', 1, ARRAY['Heart failure'], 'Cardiac pump failure causing pulmonary and systemic congestion', ARRAY['Elevated JVP', 'S3 gallop', 'Hepatomegaly'], 'The combination of dyspnea, orthopnea, and edema indicates decompensated heart failure.', 'Distinguish between systolic and diastolic dysfunction for treatment.'),
  
  ('q16', 'best_answer', 'A 7-year-old with sudden painless vision loss in one eye. What must be ruled out?', 'Ophthalmology', 3, ARRAY['Retinoblastoma'], ARRAY['A) Amblyopia', 'B) Retinoblastoma', 'C) Retinitis pigmentosa', 'D) Color blindness'], 'Pediatric cancer of the retina requiring urgent evaluation', ARRAY['White pupillary reflex (leukocoria)', 'Strabismus', 'Eye pain and glaucoma'], 'Leukocoria (white reflex) in children is retinoblastoma until proven otherwise.', 'Early detection dramatically improves outcomes.'),
  
  ('q17', 'pathognomonic', '["Saddle nose deformity"]', 'Rheumatology', 2, ARRAY['Granulomatosis with polyangiitis', 'GPA'], 'Systemic vasculitis affecting upper and lower respiratory tract', ARRAY['Glomerulonephritis', 'Necrotizing vasculitis', 'c-ANCA positive'], 'Saddle nose deformity results from nasal cartilage necrosis in GPA.', 'GPA is a medical emergency if pulmonary or renal involvement.'),
  
  ('q18', 'triad', '["Fever", "Hypotension", "Altered mental status"]', 'Infectious Disease', 1, ARRAY['Septic shock', 'Sepsis'], 'Life-threatening systemic response to infection with organ dysfunction', ARRAY['Tachycardia', 'Tachypnea', 'Elevated lactate'], 'Septic shock requires immediate antibiotics, fluid resuscitation, and vasopressors.', 'Do not delay antibiotics while waiting for culture results.'),
  
  ('q19', 'best_answer', 'A young woman with amenorrhea, hirsutism, and acne. What is the most likely diagnosis?', 'Endocrinology', 2, ARRAY['PCOS', 'Polycystic ovary syndrome'], ARRAY['A) Hypothyroidism', 'B) PCOS', 'C) Prolactinoma', 'D) Cushing syndrome'], 'Most common cause of hyperandrogenism and infertility in women', ARRAY['Insulin resistance', 'Obesity', 'Polycystic ovaries on ultrasound'], 'PCOS is diagnosed by Rotterdam criteria (2 of 3 features).', 'PCOS requires screening for metabolic syndrome and diabetes.'),
  
  ('q20', 'pathognomonic', '["Bull\'s eye lesion on skin"]', 'Infectious Disease', 2, ARRAY['Erythema migrans', 'Lyme disease'], 'Tick-borne spirochete infection causing expanding erythema', ARRAY['Central clearing', 'Migratory pattern', 'Often asymptomatic'], 'Erythema migrans (target lesion) is pathognomonic for early Lyme disease.', 'Lyme disease can progress to serious complications without treatment.'),
  
  ('q21', 'triad', '["Telangiectasia", "Bleeding tendency", "Recurrent infections"]', 'Hematology', 2, ARRAY['Ataxia-telangiectasia'], 'Autosomal recessive disorder affecting DNA repair', ARRAY['Cerebellar ataxia', 'Immunodeficiency', 'Cancer predisposition'], 'AT presents with progressive neurologic decline and immunodeficiency.', 'Patients have extreme radiosensitivity.'),
  
  ('q22', 'best_answer', 'A patient with joint pain, photosensitive rash, and positive ANA. What is the most likely diagnosis?', 'Rheumatology', 2, ARRAY['Systemic lupus erythematosus', 'SLE'], ARRAY['A) Rheumatoid arthritis', 'B) SLE', 'C) Scleroderma', 'D) Sjögren syndrome'], 'Multisystem autoimmune disease with constitutional and organ involvement', ARRAY['Malar rash', 'Discoid lesions', 'Oral ulcers'], 'SLE diagnosis requires 4 of 11 ACR/EULAR criteria.', 'Monitor for lupus nephritis and CNS involvement.'),
  
  ('q23', 'pathognomonic', '["Pancreatic calcification on imaging"]', 'Gastroenterology', 2, ARRAY['Chronic pancreatitis'], 'Long-standing inflammation of pancreas causing fibrosis', ARRAY['Steatorrhea', 'Diabetes mellitus', 'Pancreatic insufficiency'], 'Pancreatic calcification indicates irreversible chronic pancreatitis.', 'Chronic pancreatitis requires enzyme replacement and pain management.'),
  
  ('q24', 'triad', '["Night sweats", "Weight loss", "Fever"]', 'Infectious Disease', 1, ARRAY['Tuberculosis', 'TB'], 'Chronic mycobacterial infection affecting lungs primarily', ARRAY['Cough with hemoptysis', 'Upper lobe cavitation', 'Positive AFB smear'], 'Constitutional symptoms with pulmonary findings suggest active tuberculosis.', 'TB is contagious and requires isolation and directly observed therapy.'),
  
  ('q25', 'best_answer', 'A 3-month-old with blue baby appearance and feeding difficulty. What must be considered?', 'Pediatrics', 2, ARRAY['Cyanotic congenital heart disease'], ARRAY['A) Pneumonia', 'B) Congenital heart disease', 'C) Asthma', 'D) Foreign body'], 'Right-to-left cardiac shunt causing desaturation', ARRAY['Hypercyanotic episodes', 'Failure to thrive', 'Murmur on exam'], 'Cyanosis in infancy suggests structural cardiac disease until proven otherwise.', 'Prostaglandin E1 keeps ductus arteriosus open as temporary measure.');
